spring.datasource.username=${DB_USERNAME:jira}
spring.datasource.password=${DB_PASSWORD:JiraRush}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:test}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:test}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:test}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:test}

spring.security.oauth2.client.registration.gitlab.client-id=${GITLAB_CLIENT_ID:test}
spring.security.oauth2.client.registration.gitlab.client-secret=${GITLAB_CLIENT_SECRET:test}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:test}
spring.mail.password=${MAIL_PASSWORD:test}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:false}